//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetodosPagoUsuario
    {
        public int Id { get; set; }
        public System.Guid UsuarioId { get; set; }
        public int MetodoPagoId { get; set; }
        public string NumeroTarjeta { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string NombreTitular { get; set; }
        public string CuentaPaypal { get; set; }
        public string CuentaMercadoPago { get; set; }
        public bool Activo { get; set; }
        public bool EsPredeterminado { get; set; }
    
        public virtual MetodosPago MetodosPago { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
