//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NovaMerEntities2 : DbContext
    {
        public NovaMerEntities2()
            : base("name=NovaMerEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RolUsuario> RolUsuarios { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<ImgProducto> ImgProductoes { get; set; }
        public virtual DbSet<Direccione> Direcciones { get; set; }
        public virtual DbSet<MetodosPago> MetodosPagoes { get; set; }
        public virtual DbSet<MetodosPagoUsuario> MetodosPagoUsuarios { get; set; }
        public virtual DbSet<Vendedor> Vendedors { get; set; }
    }
}
