//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.DetallesPedidoes = new HashSet<DetallesPedido>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid UsuarioId { get; set; }
        public System.Guid DireccionId { get; set; }
        public System.DateTime FechaPedido { get; set; }
        public decimal Total { get; set; }
        public string Estatus { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesPedido> DetallesPedidoes { get; set; }
        public virtual Direccione Direccione { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
